### ISSUE TITLE
Potential bug - pause at 100% occurring after "in-pause" time

### ISSUE THREAD

**Issue by Boffinboy** [salewis38/palm#15]
Hi there, my AC3 died so haven't been able to test the "winter" season until today when it was finally replaced. I need to pull the new code to my fork, but I believe I have uncovered a bug. To prevent oscillations when at 100% the inverter is paused as I read the code. The inverter is un paused one hour before the end of the charge period. This morning, my inverter did not unpause and the battery charge and discharge power stayed at 0. Looking at the logs, the SOC reached 100% at 6:11 AM. The charge window ended at 7 AM, so the battery had missed the unpause window, I think?

**Comment by salewis38** [comment]
I saw this myself recently one day and it appeared that the GivEnergy
server was having a wobble.

Truth be told, the oscillation bug only manifests when SoC is set to below
100%, so I'm now running a version which disables the bug fix code under
these conditions. I'll upload it tomorrow.

Apparently the AIO has a different bug where the target SoC applies both to
AC Charge and Eco mode so needs to be reset to 100% at the end of the
overnight charge. Never simple!

**Comment by Boffinboy** [comment]
The kit isn’t half buggy! Giv engineer that replaced my AC3 inverter said they were having failure rates approaching 70% on people with firmware 3013 (one of the ones to fix the SoC jumping bug) and therefore trying to keep people on 3012. I was feeling disappointed I hadn’t waited and got the AIO, but the problems there seem to be even worse!

**Comment by salewis38** [comment]
Should work with latest commit.
Ref your comment on 3013, let's hope it's that the batteries have an underlying issue and people have tried loading 3013 to fix, rather than 3013 breaking perfectly good batteries... not good either way!
