### ISSUE TITLE
Solcast API changes

### ISSUE THREAD

**Issue by britkat1980** [salewis38/palm#17]
Now that Solcast have changed their API licencing, PALM no longer runs under GivTCP, are you able to fix, or will we need to retire PALM from v3 of GivTCP?

Thanks

**Comment by salewis38** [comment]
PALM is not running under GivTCP because there is a field missing in  palm_settings.py. PALM still works with Solcast in standalone mode, so I can see no reason why it shouldn't still work in GivTCP too.

Extra information added to palm_settings.py and pull request raised.
